name: dfix
version: 0.3.5
summary: The dfix is a tool for automatically upgrading D source code
description: |
    The dfix, is a cross platform tool for automatically upgrading D source code. 
    It's used by several text editors and IDE to get IDE-grade features.
confinement: classic
grade: stable

apps:
  dfix:
    command: bin/dfix

parts:
  dfix:
    source: https://github.com/dlang-community/dfix.git
    source-tag: v0.3.5
    source-type: git
    plugin: make
    makefile: makefile
    make-parameters:
      - DMD=/snap/bin/dmd
    artifacts:
      - bin/dfix
    build-snaps:
    - dmd
    build-packages:
    - build-essential
