name: dfix
version: 0.3.5
summary: Developer tool to auto-upgrade D source code
description: |
  Command-line utility to automate the process of upgrading D source code
  from old or deprecated syntax to newer forms.
confinement: classic
grade: stable

apps:
  dfix:
    command: bin/dfix

parts:
  dfix:
    source: https://github.com/dlang-community/dfix.git
    source-tag: v0.3.5
    source-type: git
    plugin: make
    makefile: makefile
    make-parameters:
      - DMD=/snap/bin/dmd
    artifacts:
      - bin/dfix
    build-snaps:
    - dmd
    build-packages:
    - build-essential
